import { Fragment } from "react";
import Head from "next/head";
import MainNavigation from "./mainNavigation";
import styles from "./layout.module.css";

//import MainNavigation from "./main-navigation";

const Layout = (props) => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`h-100 ${styles.MainWrap}`}>
        <div className="d-flex h-100">
            <MainNavigation />
            
            <section className={`h-100 ${styles.MainSection}`}> 
              {props.children}
            </section>
        </div>
      </main>

      {/*<Footer />*/}
    </Fragment>
  );
};

export default Layout;
